categories = [
    # Business
    ["business", "entrepreneurial"],
    ["business", "strategic"],
    ["business", "financial"],
    ["business", "management"],
    ["business", "marketing"],
    ["business", "sales"],
    ["business", "operations"],
    ["business", "investment"],
    ["business", "accounting"],
    ["business", "economics"],
    ["business", "negotiation"],
    ["business", "consulting"],
    ["business", "analytics"],
    ["business", "project management"],
    ["business", "branding"],
    ["business", "customer service"],
    ["business", "human resources"],
    ["business", "supply chain"],
    ["business", "risk management"],
    ["business", "strategic planning"],
    ["business", "innovation"],
    ["business", "entrepreneurship"],
    ["business", "corporate finance"],
    ["business", "venture capital"],
    ["business", "e-commerce"],
    ["business", "product management"],
    ["business", "startups"],
    ["business", "operations management"],
    ["business", "profitability"],
    ["business", "market research"],
    ["business", "logistics"],
    ["business", "franchising"],
    # Finance
    ["finance", "budgeting"],
    ["finance", "accounting"],
    ["finance", "portfolio management"],
    ["finance", "risk management"],
    ["finance", "capital markets"],
    ["finance", "asset management"],
    ["finance", "taxation"],
    ["finance", "banking"],
    ["finance", "corporate finance"],
    ["finance", "investment banking"],
    ["finance", "financial reporting"],
    ["finance", "audit"],
    ["finance", "valuation"],
    ["finance", "hedging"],
    ["finance", "private equity"],
    ["finance", "venture capital"],
    ["finance", "financial modeling"],
    ["finance", "credit analysis"],
    ["finance", "economic forecasting"],
    ["finance", "mergers and acquisitions"],
    ["finance", "liquidity management"],
    ["finance", "cost control"],
    ["finance", "financial regulation"],
    ["finance", "equity"],
    ["finance", "derivatives"],
    ["finance", "treasury management"],
    ["finance", "fund management"],
    ["finance", "revenue management"],
    ["finance", "sustainable finance"],
    ["finance", "insurance"],
    ["finance", "financial engineering"],
    ["finance", "real estate finance"],
    ["finance", "retirement planning"],
    # Marketing
    ["marketing", "branding"],
    ["marketing", "advertising"],
    ["marketing", "digital marketing"],
    ["marketing", "content marketing"],
    ["marketing", "social media"],
    ["marketing", "SEO"],
    ["marketing", "PPC"],
    ["marketing", "email marketing"],
    ["marketing", "market research"],
    ["marketing", "consumer behavior"],
    ["marketing", "public relations"],
    ["marketing", "campaign management"],
    ["marketing", "market segmentation"],
    ["marketing", "customer engagement"],
    ["marketing", "influencer marketing"],
    ["marketing", "lead generation"],
    ["marketing", "conversion rate optimization"],
    ["marketing", "marketing automation"],
    ["marketing", "strategic marketing"],
    ["marketing", "event marketing"],
    ["marketing", "analytics"],
    ["marketing", "product marketing"],
    ["marketing", "competitive analysis"],
    ["marketing", "sales enablement"],
    ["marketing", "affiliate marketing"],
    ["marketing", "mobile marketing"],
    ["marketing", "content strategy"],
    ["marketing", "customer journey"],
    ["marketing", "growth hacking"],
    ["marketing", "advertising campaign"],
    ["marketing", "digital advertising"],
    ["marketing", "media planning"],
    ["marketing", "brand management"],
    ["marketing", "promotions"],
    ["marketing", "pricing strategy"],
    ["marketing", "loyalty programs"],
    ["marketing", "customer retention"],
    ["marketing", "market positioning"],
    # Physics
    ["physics", "quantum mechanics"],
    ["physics", "thermodynamics"],
    ["physics", "electromagnetism"],
    ["physics", "relativity"],
    ["physics", "nuclear physics"],
    ["physics", "particle physics"],
    ["physics", "optics"],
    ["physics", "acoustics"],
    ["physics", "fluid dynamics"],
    ["physics", "statistical mechanics"],
    ["physics", "solid state physics"],
    ["physics", "atomic physics"],
    ["physics", "astrophysics"],
    ["physics", "cosmology"],
    ["physics", "plasma physics"],
    ["physics", "gravitation"],
    ["physics", "magnetism"],
    ["physics", "wave physics"],
    ["physics", "field theory"],
    ["physics", "high energy physics"],
    ["physics", "condensed matter physics"],
    ["physics", "nuclear fusion"],
    ["physics", "radioactivity"],
    ["physics", "nuclear decay"],
    ["physics", "quantum field theory"],
    ["physics", "experimental physics"],
    ["physics", "theoretical physics"],
    ["physics", "mathematical physics"],
    ["physics", "optical physics"],
    ["physics", "particle acceleration"],
    ["physics", "nonlinear dynamics"],
    ["physics", "geophysics"],
    ["physics", "biophysics"],
    ["physics", "surface physics"],
    # Chemistry
    ["chemistry", "organic chemistry"],
    ["chemistry", "inorganic chemistry"],
    ["chemistry", "physical chemistry"],
    ["chemistry", "analytical chemistry"],
    ["chemistry", "biochemistry"],
    ["chemistry", "thermochemistry"],
    ["chemistry", "reaction kinetics"],
    ["chemistry", "stoichiometry"],
    ["chemistry", "chemical bonding"],
    ["chemistry", "molecular structure"],
    ["chemistry", "spectroscopy"],
    ["chemistry", "chromatography"],
    ["chemistry", "electrochemistry"],
    ["chemistry", "coordination chemistry"],
    ["chemistry", "thermodynamics"],
    ["chemistry", "quantum chemistry"],
    ["chemistry", "solutions"],
    ["chemistry", "acids and bases"],
    ["chemistry", "redox reactions"],
    ["chemistry", "material science"],
    ["chemistry", "polymer chemistry"],
    ["chemistry", "nanochemistry"],
    ["chemistry", "chemical equilibrium"],
    ["chemistry", "reactivity"],
    ["chemistry", "organic synthesis"],
    ["chemistry", "analytical techniques"],
    ["chemistry", "chemical kinetics"],
    ["chemistry", "bioinorganic chemistry"],
    ["chemistry", "chemical safety"],
    ["chemistry", "laboratory techniques"],
    ["chemistry", "pharmaceutical chemistry"],
    ["chemistry", "green chemistry"],
    ["chemistry", "medicinal chemistry"],
    ["chemistry", "environmental chemistry"],
    ["chemistry", "industrial chemistry"],
    ["chemistry", "food chemistry"],
    ["chemistry", "forensic chemistry"],
    # Biology
    ["biology", "genetics"],
    ["biology", "evolution"],
    ["biology", "biochemistry"],
    ["biology", "ecology"],
    ["biology", "physiology"],
    ["biology", "anatomy"],
    ["biology", "microbiology"],
    ["biology", "botany"],
    ["biology", "zoology"],
    ["biology", "immunology"],
    ["biology", "neuroscience"],
    ["biology", "genomics"],
    ["biology", "biotechnology"],
    ["biology", "biomedical science"],
    ["biology", "cell signaling"],
    ["biology", "biophysics"],
    ["biology", "molecular genetics"],
    ["biology", "pharmacology"],
    ["biology", "endocrinology"],
    ["biology", "entomology"],
    ["biology", "wildlife biology"],
    ["biology", "parasitology"],
    ["biology", "virology"],
    ["biology", "human genetics"],
    # Technology
    ["technology", "cybersecurity"],
    ["technology", "networking"],
    ["technology", "3D printing"],
    ["technology", "innovation"],
    ["technology", "engineering"],
    ["computer science", "software"],
    ["coding", "code"],
    ["technology", "programming"],
    ["program", "programming"],
    ["computer science", "development"],
    ["technology", "photoshop"],
    ["technology", "illustrator"],
    ["computer science", "AI"],
    ["computer science", "machine learning"],
    ["computer science", "data science"],
    ["technology", "cloud computing"],
    ["technology", "big data"],
    ["technology", "blockchain"],
    ["technology", "internet of things"],
    ["technology", "robotics", "engineering"],
    ["technology", "augmented reality"],
    ["technology", "virtual reality"],
    ["technology", "web development"],
    ["technology", "mobile apps"],
    ["technology", "UX/UI design"],
    ["technology", "database management"],
    ["technology", "network administration"],
    ["technology", "IT support"],
    ["technology", "game development"],
    ["technology", "quantum computing"],
    ["technology", "automation"],
    ["technology", "electronics"],
    ["technology", "telecommunications"],
    ["technology", "embedded systems"],
    ["technology", "digital media"],
    ["technology", "software engineering"],
    ["technology", "hardware"],
    # Arts
    ["arts", "art"],
    ["arts", "printmaking"],
    ["arts", "graphic design"],
    ["arts", "illustration"],
    ["arts", "collage"],
    ["arts", "craftsmanship"],
    ["arts", "jewelry design"],
    ["arts", "furniture design"],
    ["arts", "interior design"],
    ["arts", "landscape design"],
    ["arts", "cultural heritage"],
    ["arts", "museum studies"],
    ["arts", "performance"],
    ["acting", "theatre"],
    ["drama", "theatre"],
    ["arts", "acting"],
    ["arts", "directing"],
    ["arts", "musical theatre"],
    ["arts", "playwriting"],
    ["arts", "choreography"],
    ["arts", "opera"],
    # Music
    ["music", "classical"],
    ["music", "jazz"],
    ["music", "rock"],
    ["music", "pop"],
    ["music", "blues"],
    ["music", "country"],
    ["music", "hip-hop"],
    ["music", "rap"],
    ["music", "electronic"],
    ["music", "folk"],
    ["music", "reggae"],
    ["music", "soul"],
    ["music", "R&B"],
    ["music", "metal"],
    ["music", "punk"],
    ["music", "ambient"],
    ["music", "synthwave"],
    ["music", "opera"],
    ["music", "musical theatre"],
    ["music", "soundtrack"],
    ["music", "new age"],
    ["music", "traditional"],
    ["music", "world music"],
    ["music", "experimental"],
    ["music", "indie"],
    ["music", "acoustic"],
    ["music", "alternative"],
    ["music", "chamber music"],
    ["music", "orchestral"],
    ["music", "a cappella"],
    ["music", "vocal"],
    ["music", "instrumental"],
    ["music", "composing"],
    ["music", "arranging"],
    ["music", "recording"],
    ["music", "producing"],
    ["music", "live performance"],
    ["music", "improvisation"],
    ["music", "music theory"],
    ["music", "ethnomusicology"],
    ["music", "music education"],
    ["music", "music therapy"],
    # Sports
    ["sports", "soccer"],
    ["sports", "basketball"],
    ["sports", "tennis"],
    ["sports", "volleyball"],
    ["sports", "baseball"],
    ["sports", "football (American)"],
    ["sports", "rugby"],
    ["sports", "hockey"],
    ["sports", "golf"],
    ["sports", "swimming"],
    ["sports", "track and field"],
    ["sports", "gymnastics"],
    ["sports", "martial arts"],
    ["sports", "wrestling"],
    ["sports", "cycling"],
    ["sports", "skiing"],
    ["sports", "snowboarding"],
    ["sports", "surfing"],
    ["sports", "cricket"],
    ["sports", "badminton"],
    ["sports", "athletics"],
    ["sports", "rowing"],
    ["sports", "triathlon"],
    ["sports", "archery"],
    ["sports", "fencing"],
    ["sports", "horse racing"],
    ["sports", "kayaking"],
    ["sports", "sailing"],
    ["sports", "scuba diving"],
    ["sports", "skydiving"],
    ["sports", "bobsled"],
    ["sports", "luge"],
    ["sports", "skeleton"],
    ["sports", "pole vault"],
    ["sports", "discus"],
    ["sports", "shot put"],
    ["sports", "javelin"],
    ["sports", "hammer throw"],
    ["sports", "high jump"],
    ["sports", "long jump"],
    ["sports", "trampoline"],
    ["sports", "synchronized swimming"],
    ["sports", "water polo"],
    ["sports", "field hockey"],
    ["sports", "table tennis"],
    ["sports", "handball"],
    ["sports", "floorball"],
    ["sports", "pickleball"],
    ["sports", "equestrian"],
    ["sports", "snowshoeing"],
    ["sports", "curling"],
    ["sports", "sledge hockey"],
    ["sports", "speed skating"],
    ["sports", "weights"],
    ["sports", "ball"],
    # Food & Nutrition
    ["food", "eating"],
    ["food", "nutrition"],
    ["food", "dietary habits"],
    ["food", "food science"],
    ["food", "culinary arts"],
    ["food", "gourmet"],
    ["food", "healthy eating"],
    ["food", "dietetics"],
    ["food", "food safety"],
    ["food", "food preparation"],
    ["food", "food chemistry"],
    ["food", "nutritional analysis"],
    ["food", "culinary techniques"],
    ["food", "nutrition education"],
    ["food", "meal planning"],
    ["food", "food preservation"],
    ["food", "sustainable eating"],
    ["food", "food policy"],
    ["food", "food trends"],
    ["food", "special diets"],
    ["food", "food culture"],
    ["food", "restaurant management"],
    ["food", "food styling"],
    ["food", "food writing"],
    ["food", "beverage studies"],
    ["food", "food pairing"],
    ["food", "catering"],
    ["food", "baking"],
    ["food", "confectionery"],
    ["food", "nutrition therapy"],
    ["food", "food history"],
    ["food", "organic foods"],
    ["food", "food microbiology"],
    ["food", "dietary supplements"],
    ["food", "cooking"],
    # Health & Physical Education
    ["health", "physical fitness"],
    ["health", "nutrition"],
    ["health", "mental health"],
    ["health", "wellness"],
    ["health", "physical therapy"],
    ["health", "public health"],
    ["health", "sports medicine"],
    ["health", "exercise science"],
    ["health", "preventive health"],
    ["health", "rehabilitation"],
    ["health", "health education"],
    ["health", "first aid"],
    ["health", "emergency care"],
    ["health", "health promotion"],
    ["health", "kinesiology"],
    ["health", "occupational therapy"],
    ["health", "pediatrics"],
    ["health", "geriatrics"],
    ["health", "cardiovascular health"],
    ["health", "respiratory health"],
    ["health", "endocrinology"],
    ["health", "immunization"],
    ["health", "sleep health"],
    ["health", "chronic disease management"],
    ["health", "health policy"],
    ["health", "global health"],
    ["health", "integrative health"],
    ["health", "fitness training"],
    ["health", "sports psychology"],
    ["health", "nutrition science"],
    ["health", "health behavior"],
    ["health", "sports coaching"],
    ["health", "meditation"],
    ["health", "alternative medicine"],
    ["health", "herbal medicine"],
    ["health", "acupuncture"],
    ["health", "massage therapy"],
    # Programs linkage:
    ["doctor", "biology", "chemistry", "physics"],
    ["engineer", "physics", "computer science", "engineering"],
    ["physicist", "physics", "chemistry"],
    ["chemist", "chemistry", "biology"],
    ["biologist", "biology", "chemistry"],
    ["architect", "physics", "art"],
    ["artist", "art", "design"],
    ["economist", "economics", "business studies"],
    ["psychologist", "psychology", "biology"],
    ["lawyer", "history", "law", "english"],
    ["teacher", "english", "science"],
    ["nurse", "biology", "chemistry", "health studies"],
    ["programmer", "computer science", "physics"],
    ["journalist", "english", "history", "government"],
    ["social worker", "psychology", "sociology", "english"],
    ["chief", "cook", "cooking"],
    ["accountant", "business", "accounting"],
]
