name: Sync API to Master

on:
  push:
    branches:
      - API  # Runs when API branch is updated

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge API into master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin API
          git merge --no-edit origin/API || true
          git push origin master
